[bootstrap.packages]
"pacman:base-devel" = "latest"
"pacman:emacs" = "latest"
"pacman:fzf" = "latest"
"pacman:ghq" = "latest"
"pacman:git" = "latest"
"pacman:stumpwm" = "latest"
"pacman:ripgrep" = "latest"
"pacman:docker" = "latest"
"pacman:jq" = "latest"
"pacman:fish" = "latest"
"pacman:tmux" = "latest"
"pacman:xorg-server" = "latest"
"pacman:xorg-xmodmap" = "latest"
"pacman:xorg-xset" = "latest"
"pacman:xorg-xinit" = "latest"
"pacman:racket" = "latest"
"pacman:arandr" = "latest"
"pacman:atop" = "latest"
"pacman:zram-generator" = "latest"
"pacman:earlyoom" = "latest"
"pacman:qt5-base" = "latest"

[dotfiles]
"~/.emacs.d" = { source = ".emacs.d", mode = "symlink" }
"~/.config/starship.toml" = { source = "starship/starship.toml", mode = "symlink" }
"~/.config/stumpwm" = { source = "stumpwm/stumpwm", mode = "symlink" }
"~/.config/fish" = { source = "fish/fish", mode = "symlink" }
"~/.config/tmux" = { source = "tmux/tmux", mode = "symlink" }
"~/.uim.d/customs" = { source = "uim", mode = "symlink" }
"~/.bashrc" = { source = "bash/.bashrc", mode = "symlink" }
"~/.bash_profile" = { source = "bash/.bash_profile", mode = "symlink" }
"~/.gitconfig" = { source = "git/.gitconfig", mode = "symlink" }
"~/.gitconfig.local" = { source = "git/.gitconfig.local", mode = "symlink" }
"~/.gitignore" = { source = "git/.gitignore", mode = "symlink" }
"~/.Xmodmap" = { source = "xmodmap/.Xmodmap", mode = "symlink" }
"~/.xinitrc" = { source = "xwindow/.xinitrc", mode = "symlink" }
"~/.xprofile" = { source = "xwindow/.xprofile", mode = "symlink" }
"~/.Xresources" = { source = "xwindow/.Xresources", mode = "symlink" }
"~/.utoprc" = { source = "utop/.utoprc", mode = "symlink" }

[bootstrap.services.docker]
state = "running"
enabled = true

[bootstrap.services.earlyoom]
state = "running"
enabled = true

[bootstrap.hooks.post-dotfiles]
run = "printf '\\033[1;31m edit .gitconfig.local \\033[m\\n'"

[bootstrap.hooks.post-packages]
run = [
  """
if ! command -v yay &> /dev/null; then
  git clone https://aur.archlinux.org/yay.git /tmp/yay-bin
  cd /tmp/yay-bin && makepkg -si --noconfirm
  rm -rf /tmp/yay-bin
fi""",
"""
yay -S --noconfirm --needed \
  google-chrome \
  slack-desktop \
  noto-fonts \
  noto-fonts-cjk \
  github-cli \
  ttf-hackgen \
  starship \
  uim
"""
]

[tasks.bootstrap]
run = "gh auth status || gh auth login"
