set -sg escape-time 1

set-option -g default-terminal "tmux-256color"

set -g terminal-overrides 'xterm:color-256'

set-option -g default-shell "/usr/bin/fish"

set-option -g history-limit 50000

### status line
set -g status 2

set -g status-interval 30

set -g status-right-length 150

set -g status-format[0] "#{W: #{?window_active,#[fg=black]#[bold],#[fg=white]}#I:#W#F } #[align=right] #(echo '#{pane_current_path}' | sed \"s|^$HOME|~|\")"

set -g status-format[1] "#(bash $HOME/.config/tmux/pullreq-status-line.sh #{pane_current_path}) #[align=right] %H:%M"

### key bind
unbind C-b

set -g prefix C-q

bind-key C-q send-prefix

bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded config file"

bind-key -T copy-mode M-w send-keys -X copy-pipe "xsel -bi"

bind-key -n C-t display-popup -w 80% -h 80% -E "tmux list-sessions -F '#{session_name}' | fzf --prompt='Select Session> ' --header '↑↓ to move, Enter to switch' | xargs tmux switch-client -t"

bind-key -n C-o display-popup -d "#{pane_current_path}" -w 50% -h 40% -E "bash $HOME/.config/tmux/gh.sh"