(define custom-preserved-default-im-name 'skk)
(define default-im-name 'skk)
(define enabled-im-list '(skk))
(define enable-im-switch? #f)
(define switch-im-key '("<IgnoreCase><Control>j" "zenkaku-hankaku"))
(define switch-im-key? (make-key-predicate '("<IgnoreCase><Control>j" "zenkaku-hankaku")))
(define switch-im-skip-direct-im? #t)
(define enable-im-toggle? #t)
(define toggle-im-key '("<IgnoreCase><Control>j"))
(define toggle-im-key? (make-key-predicate '("<IgnoreCase><Control>j")))
(define toggle-im-alt-im 'skk)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
